spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpaprac?MVCC=TRUE
    username: jiwon
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc.batch_size:  100

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace